/** Synthetic API-contract examples, never represented as production captures. */
export const identity = { ticker: 'BA', cik: '0000012927', company_name: 'BOEING CO', issuer_tickers: ['BA'] };
export const meta = { window_start: '2026-07-10', window_end: '2026-10-10', window_clamped: false, date_basis: 'action_date', period: '1Q', scope: 'company', match_status: 'has_actions', provisional_from: '2026-06-01', refreshed_at: '2026-10-09T16:42:10Z', caveats: ['prime_contracts_only', 'signed_obligations', 'listed_today_survivorship', 'current_parent_not_historical'], identity, total_count: 1, page: 1, per_page: 50 };
export const action = { transaction_id: 'TX1', award_id: 'CONT_AWD_X', piid: 'N0001924C0012', modification_number: 'P00017', action_date: '2026-10-06', obligated_amount: '-1250000.00', award_type: 'D', agency: { code: '097', name: 'DEPT OF DEFENSE', sub_code: '2100', sub_name: 'ARMY' }, recipient: { name: 'BOEING', uei: 'NU2UC8MX6NK1', parent_name: 'BOEING', parent_uei: 'NU2UC8MX6NK1' }, naics: { code: '336411', description: 'AIRCRAFT' }, psc: { code: '1510', description: 'AIRCRAFT' }, place_of_performance: { country: 'USA', state: 'MO', city: 'SAINT LOUIS' }, description: 'Modification', link_tier: 'A', provisional: true, source_url: 'https://www.usaspending.gov/award/CONT_AWD_X/' };
export const totals = { gross_obligated: '10000000.00', deobligated: '-1250000.00', net_obligated: '8750000.00', actions: 2, awards: 1, agencies: 1 };
export const award = { award_id: action.award_id, piid: action.piid, award_type: 'D', agency: action.agency, recipient: action.recipient, award_description: 'Aircraft procurement', latest_action_date: action.action_date, attributed_actions: null, attributed_net_obligated: null, attributed_scope: 'issuer_attributed_since_fy2015', requires_plan: 'developer', source_url: action.source_url };
export function summary(empty = false) {
  return { data: { ...identity, totals: empty ? { gross_obligated: '0.00', deobligated: '0.00', net_obligated: '0.00', actions: 0, awards: 0, agencies: 0 } : totals, monthly: empty ? [] : [{ month: '2026-10-01', ...totals, provisional: true, window_clipped: true }], agencies: empty ? [] : [{ code: '097', name: 'DEPT OF DEFENSE', gross_obligated: totals.gross_obligated, net_obligated: totals.net_obligated, actions: 2, gross_share: 1 }], link_tiers: empty ? [] : [{ link_tier: 'A', actions: 2 }] }, meta: { ...meta, match_status: empty ? 'no_attributed_actions' : 'has_actions' } };
}
export function transactions(empty = false, scoped = false) { return { data: empty ? [] : [action], meta: { ...meta, total_count: empty ? 0 : 1, scope: scoped ? 'award' : 'company', match_status: empty ? 'none_in_window' : 'has_actions', award: scoped ? award : null } }; }
export function feed(empty = false) { return { data: empty ? [] : [{ ...action, ...identity }], meta: { ...meta, total_count: empty ? 0 : 1 } }; }
export function companies(empty = false) { return { data: empty ? [] : [{ rank: 1, ...identity, ...totals }], meta: { ...meta, total_count: empty ? 0 : 1, universe: 'listed_companies_plus_reviewed_links' } }; }
